#!/bin/bash
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py
python word_cutting.py